repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
        - --args=-diff
        - --args=-write=true
    - id: terraform_validate
    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--skip-check CKV_TF_1,CKV_TF_2
