# Use the provided base image
FROM docker.litellm.ai/berriai/litellm:main-stable

# Set the working directory to /app
WORKDIR /app

# Copy the configuration file into the container at /app
COPY config.yaml .

# Expose the necessary port
EXPOSE 4000/tcp

CMD ["--port", "4000", "--config", "config.yaml", "--detailed_debug"]
